ASP_WebAppTour_6AKIF_JaenV/Models/Kunde.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_WebAppTour_6AKIF_JaenV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Buchungs = new HashSet<Buchung>();
        }
    
        public int K_Kunde_Id { get; set; }
        public string K_Vorname { get; set; }
        public string K_Nachname { get; set; }
        public Nullable<System.DateTime> K_GebDatum { get; set; }
        public string K_Strasse { get; set; }
        public string K_Hausnr { get; set; }
        public string K_Ort { get; set; }
        public string K_Land { get; set; }
        public string K_PLZ { get; set; }
        public string K_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
    }
}

ASP_WebAppTour_6AKIF_JaenV/Controllers/BuchungController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASP_WebAppTour_6AKIF_JaenV.Models;

namespace ASP_WebAppTour_6AKIF_JaenV.Controllers
{
    [Authorize (Users ="Jaen")]
    public class BuchungController : Controller
    {

        private Tour_DBEntities db = new Tour_DBEntities();

        // GET: Buchung
        public ActionResult Index(int? suchkunde, int? suchtour)
        {
            
            var buchungs = db.Buchungs.Include(b => b.Fremdenfuehrer).Include(b => b.Kunde).Include(b => b.Sprache).Include(b => b.Tour).Include(b => b.Treffpunkt);
           if (suchkunde != null)
            {
                buchungs = buchungs.Where(b => b.B_K_Kunde_Id == suchkunde);
                ViewBag.suchkundenanzeige = "Buchungen nur von " + suchkunde;
            }
            if (suchtour != null)
            {
                buchungs = buchungs.Where(b => b.Tour.To_Tour_Id == suchtour);
            }
            ViewBag.suchkunde = new SelectList(db.Kundes, "K_Kunde_Id", "K_Vorname");
            ViewBag.suchtour = new SelectList(db.Tours, "To_Tour_Id", "To_Bezeichnung");
            return View(buchungs.ToList());
        }

        // GET: Buchung/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Buchung buchung = db.Buchungs.Find(id);
            if (buchung == null)
            {
                return HttpNotFound();
            }
            return View(buchung);
        }

        // GET: Buchung/Create
        public ActionResult Create()
        {
            ViewBag.B_F_Fremdenfuehrer_Id = new SelectList(db.Fremdenfuehrers, "F_Fremdenfuehrer_Id", "F_Vorname");
            ViewBag.B_K_Kunde_Id = new SelectList(db.Kundes, "K_Kunde_Id", "K_Vorname");
            ViewBag.B_S_Sprach_Id = new SelectList(db.Spraches, "S_Sprach_Id", "S_Language");
            ViewBag.B_To_Tour_Id = new SelectList(db.Tours, "To_Tour_Id", "To_Bezeichnung");
            ViewBag.B_T_Treffpunkt_Id = new SelectList(db.Treffpunkts, "T_Treffpunkt_Id", "T_Strasse");
            return View();
        }

        // POST: Buchung/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "B_Buchung_Id,B_Datum,B_Personenanzahl,B_Preis,B_K_Kunde_Id,B_To_Tour_Id,B_F_Fremdenfuehrer_Id,B_S_Sprach_Id,B_T_Treffpunkt_Id")] Buchung buchung)
        {
            if (ModelState.IsValid)
            {
                db.Buchungs.Add(buchung);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.B_F_Fremdenfuehrer_Id = new SelectList(db.Fremdenfuehrers, "F_Fremdenfuehrer_Id", "F_Vorname", buchung.B_F_Fremdenfuehrer_Id);
            ViewBag.B_K_Kunde_Id = new SelectList(db.Kundes, "K_Kunde_Id", "K_Vorname", buchung.B_K_Kunde_Id);
            ViewBag.B_S_Sprach_Id = new SelectList(db.Spraches, "S_Sprach_Id", "S_Language", buchung.B_S_Sprach_Id);
            ViewBag.B_To_Tour_Id = new SelectList(db.Tours, "To_Tour_Id", "To_Bezeichnung", buchung.B_To_Tour_Id);
            ViewBag.B_T_Treffpunkt_Id = new SelectList(db.Treffpunkts, "T_Treffpunkt_Id", "T_Strasse", buchung.B_T_Treffpunkt_Id);
            return View(buchung);
        }

        // GET: Buchung/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Buchung buchung = db.Buchungs.Find(id);
            if (buchung == null)
            {
                return HttpNotFound();
            }
            ViewBag.B_F_Fremdenfuehrer_Id = new SelectList(db.Fremdenfuehrers, "F_Fremdenfuehrer_Id", "F_Vorname", buchung.B_F_Fremdenfuehrer_Id);
            ViewBag.B_K_Kunde_Id = new SelectList(db.Kundes, "K_Kunde_Id", "K_Vorname", buchung.B_K_Kunde_Id);
            ViewBag.B_S_Sprach_Id = new SelectList(db.Spraches, "S_Sprach_Id", "S_Language", buchung.B_S_Sprach_Id);
            ViewBag.B_To_Tour_Id = new SelectList(db.Tours, "To_Tour_Id", "To_Bezeichnung", buchung.B_To_Tour_Id);
            ViewBag.B_T_Treffpunkt_Id = new SelectList(db.Treffpunkts, "T_Treffpunkt_Id", "T_Strasse", buchung.B_T_Treffpunkt_Id);
            return View(buchung);
        }

        // POST: Buchung/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "B_Buchung_Id,B_Datum,B_Personenanzahl,B_Preis,B_K_Kunde_Id,B_To_Tour_Id,B_F_Fremdenfuehrer_Id,B_S_Sprach_Id,B_T_Treffpunkt_Id")] Buchung buchung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(buchung).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.B_F_Fremdenfuehrer_Id = new SelectList(db.Fremdenfuehrers, "F_Fremdenfuehrer_Id", "F_Vorname", buchung.B_F_Fremdenfuehrer_Id);
            ViewBag.B_K_Kunde_Id = new SelectList(db.Kundes, "K_Kunde_Id", "K_Vorname", buchung.B_K_Kunde_Id);
            ViewBag.B_S_Sprach_Id = new SelectList(db.Spraches, "S_Sprach_Id", "S_Language", buchung.B_S_Sprach_Id);
            ViewBag.B_To_Tour_Id = new SelectList(db.Tours, "To_Tour_Id", "To_Bezeichnung", buchung.B_To_Tour_Id);
            ViewBag.B_T_Treffpunkt_Id = new SelectList(db.Treffpunkts, "T_Treffpunkt_Id", "T_Strasse", buchung.B_T_Treffpunkt_Id);
            return View(buchung);
        }

        // GET: Buchung/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Buchung buchung = db.Buchungs.Find(id);
            if (buchung == null)
            {
                return HttpNotFound();
            }
            return View(buchung);
        }

        // POST: Buchung/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Buchung buchung = db.Buchungs.Find(id);
            db.Buchungs.Remove(buchung);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASP_WebAppTour_6AKIF_JaenV/Controllers/KundeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASP_WebAppTour_6AKIF_JaenV.Models;

namespace ASP_WebAppTour_6AKIF_JaenV.Controllers
{
    [Authorize]
    public class KundeController : Controller
    {
        private Tour_DBEntities db = new Tour_DBEntities();

        // GET: Kunde
        public ActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.CitySortParm = String.IsNullOrEmpty(sortOrder) ? "city_desc" : "";
            var kundens = from k in db.Kundes
                          select k;
            switch (sortOrder)
            {
                case "name desc":
                    kundens = kundens.OrderByDescending(to => to.K_Vorname);
                    break;
                case "Date":
                    kundens = kundens.OrderByDescending(k => k.K_GebDatum);
                    break;
                case "date_desc":
                    kundens = kundens.OrderByDescending(k => k.K_GebDatum);
                    break;
                case "city_desc":
                    kundens = kundens.OrderByDescending(to => to.K_Ort);
                    break;
                default:
                    kundens = kundens.OrderBy(k => k.K_Vorname);
                    break;
            }
            return View(kundens.ToList());
        }

        // GET: Kunde/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kundes.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            return View(kunde);
        }

        // GET: Kunde/Create
        [Authorize (Users = "Jaen")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kunde/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "K_Kunde_Id,K_Vorname,K_Nachname,K_GebDatum,K_Strasse,K_Hausnr,K_Ort,K_Land,K_PLZ,K_Email")] Kunde kunde)
        {
            if (ModelState.IsValid)
            {
                db.Kundes.Add(kunde);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(kunde);
        }

        // GET: Kunde/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kundes.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            Session["lastkundeid"] = kunde.K_Kunde_Id;
            return View(kunde);
        }

        // POST: Kunde/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "K_Kunde_Id,K_Vorname,K_Nachname,K_GebDatum,K_Strasse,K_Hausnr,K_Ort,K_Land,K_PLZ,K_Email")] Kunde kunde)
        {
            kunde.K_Kunde_Id = (int)Session["lastkundeid"];
            if (ModelState.IsValid)
            {
                db.Entry(kunde).State = EntityState.Modified;
                db.SaveChanges();
                Session["lastkundeid"] = null;
                return RedirectToAction("Index");
            }
            return View(kunde);
        }

        // GET: Kunde/Delete/5
        [Authorize(Users = "Jaen")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kundes.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            return View(kunde);
        }

        // POST: Kunde/Delete/5
     
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kunde kunde = db.Kundes.Find(id);
            db.Kundes.Remove(kunde);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASP_WebAppTour_6AKIF_JaenV/Views/Kunde/Create.cshtml
@model ASP_WebAppTour_6AKIF_JaenV.Models.Kunde

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kunde</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.K_Vorname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Vorname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Vorname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Nachname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Nachname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Nachname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_GebDatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_GebDatum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_GebDatum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Strasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Strasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Strasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Hausnr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Hausnr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Hausnr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Ort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Ort, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Ort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Land, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Land, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Land, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_PLZ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_PLZ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_PLZ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.K_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.K_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.K_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASP_WebAppTour_6AKIF_JaenV/Views/Kunde/Delete.cshtml
@model ASP_WebAppTour_6AKIF_JaenV.Models.Kunde

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kunde</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.K_Vorname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Vorname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Nachname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Nachname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_GebDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_GebDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Strasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Strasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Hausnr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Hausnr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Ort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Ort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Land)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Land)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_PLZ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_PLZ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP_WebAppTour_6AKIF_JaenV/Views/Kunde/Details.cshtml
@model ASP_WebAppTour_6AKIF_JaenV.Models.Kunde

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kunde</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.K_Vorname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Vorname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Nachname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Nachname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_GebDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_GebDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Strasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Strasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Hausnr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Hausnr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Ort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Ort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Land)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Land)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_PLZ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_PLZ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.K_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.K_Email)
        </dd>
        <dt>
            Anzahl Buchungen
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => Model.Buchungs.Count)
        </dd>
        <dd>
            @foreach (var item in Model.Buchungs)
            {
                @item.B_Datum
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.K_Kunde_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASP_WebAppTour_6AKIF_JaenV/Views/Kunde/Index.cshtml
@model IEnumerable<ASP_WebAppTour_6AKIF_JaenV.Models.Kunde>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new {SortOrder = ViewBag.NameSortParm}) 
        </th>
        @* Attributierung Name: Verbindung Vorname und Nachname *@
        @*<th>
            @Html.DisplayNameFor(model => model.Name)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.K_Nachname)
        </th>*@
    <th>
        @Html.ActionLink("Geburtsdatum", "Index", new { SortOrder = ViewBag.DateSortParm })
    </th>
        @*<th>
            @Html.DisplayNameFor(model => model.K_GebDatum)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Anschrift)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.K_Hausnr)
        </th>*@
    <th>
        @Html.ActionLink("Stadt", "Index", new { SortOrder = ViewBag.CitySortParm })
        @*@Html.DisplayNameFor(model => model.K_Ort)*@
    </th>
        <th>
            @Html.DisplayNameFor(model => model.K_Land)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.K_PLZ)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.K_Email)
        </th>
        <th>
            Anzahl Buchungen
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.K_Nachname)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.K_GebDatum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Anschrift)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.K_Hausnr)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.K_Ort)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.K_Land)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.K_PLZ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.K_Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Buchungs.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.K_Kunde_Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.K_Kunde_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.K_Kunde_Id })
            @Html.ActionLink("zeige Buchungen", "Index", "Buchung", new { suchkunde = item.K_Kunde_Id }, null)
        </td>
    </tr>
}

</table>